for i in range(1, 5):              
    print("name = input('What is my name(hint: it may or may not be Saksham): ')")
    print("name = name.upper()")
    print("if name == 'SAKSHAM':")
    print("    Good job!")
    print("    print(' ') ")    
    print("else:")
    print("    print('YOU WERE NEVER SUPPOSED TO FAIL THIS PART! YOU ARE STUPID')")
    print("    print(' ')")
    print("    sys.exit()")
